[book]
title = "Rust Embedded MB2 Discovery Book (日本語訳)"
description = "BBC micro:bit v2 を通してマイクロコントローラの世界を Rust で探求する"
authors = ["Rust Embedded Resources Team"]
language = "ja"

[output.html]
git-repository-url = "https://github.com/rust-embedded/discovery-mb2/"
additional-js = ["src/assets/epub-link.js"]
additional-css = ["src/assets/custom.css"]

[output.epub]
optional = false
title = "Rust Embedded MB2 Discovery Book (日本語訳)"
author = "Rust Embedded Resources Team"

# [output.html.site]
# url = "/"
# Optional settings
# base-url = "/discovery-mb2/"
# git-repository-url = "
